alias c="clear"
alias s="sudo"
alias m="micro"
alias l="ll"
alias x="exit"
alias top="htop"
alias cat="bat --theme=1337"
alias ping="prettyping --nolegend"
alias ls="lsd"
alias ll="lsd -l"
alias diff="diff-so-fancy"
